In [1]:
import numpy as np
import tensorflow as tf
import keras 
import matplotlib.pyplot as plt
from PIL import Image
import random
import cv2
from tensorflow.keras.models import Model,load_model

from tensorflow.keras import Sequential
from tensorflow.keras import datasets,layers,models
from tensorflow.keras.layers import Conv2D, MaxPool2D, Flatten, Dense,Dropout
from tensorflow.keras.preprocessing.image import ImageDataGenerator
 

In [2]:
train_dir = 'train' 
valid_dir = 'valid'   


In [ ]:
training_set = keras.utils.image_dataset_from_directory(
    directory="train",  
    labels="inferred",
    label_mode="categorical", 
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
   )


In [ ]:
validation_set = keras.utils.image_dataset_from_directory(
    directory="valid",
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
)


In [ ]:
training_set

In [15]:
validation_set

<_PrefetchDataset element_spec=(TensorSpec(shape=(None, 128, 128, 3), dtype=tf.float32, name=None), TensorSpec(shape=(None, 38), dtype=tf.float32, name=None))>

In [16]:
for x,y in training_set:
    print(x)
    print(y)
    break


tf.Tensor(
[[[[186.75 178.75 189.75]
   [173.   165.   176.  ]
   [160.25 152.25 163.25]
   ...
   [189.75 183.75 193.75]
   [184.5  178.5  188.5 ]
   [184.5  178.5  188.5 ]]

  [[177.   169.   180.  ]
   [173.75 165.75 176.75]
   [160.5  152.5  163.5 ]
   ...
   [191.5  185.5  195.5 ]
   [189.75 183.75 193.75]
   [187.   181.   191.  ]]

  [[182.   174.   185.  ]
   [163.25 155.25 166.25]
   [150.5  142.5  153.5 ]
   ...
   [188.25 182.25 192.25]
   [189.25 183.25 193.25]
   [196.25 190.25 200.25]]

  ...

  [[143.5  133.5  142.5 ]
   [144.75 134.75 143.75]
   [146.5  136.5  145.5 ]
   ...
   [170.5  162.5  173.5 ]
   [150.5  142.5  153.5 ]
   [149.25 141.25 152.25]]

  [[133.25 123.25 132.25]
   [144.75 134.75 143.75]
   [145.   135.   144.  ]
   ...
   [157.5  149.5  160.5 ]
   [167.75 159.75 170.75]
   [149.   141.   152.  ]]

  [[142.25 132.25 141.25]
   [139.75 129.75 138.75]
   [150.   140.   149.  ]
   ...
   [161.   153.   164.  ]
   [177.25 169.25 180.25]
   [172.75 164.75 17

In [8]:
model= tf.keras.models.Sequential()

In [9]:
import tensorflow as tf

model.add(tf.keras.layers.Conv2D(filters=32, kernel_size=3, padding="same", activation="relu", input_shape=[128, 128, 3]))
model.add(tf.keras.layers.Conv2D(filters=32, kernel_size=3, activation="relu"))
model.add(tf.keras.layers.MaxPool2D(pool_size=2, strides=2))

model.add(tf.keras.layers.Conv2D(filters=64, kernel_size=3, padding="same", activation="relu"))
model.add(tf.keras.layers.Conv2D(filters=64, kernel_size=3, activation="relu"))
model.add(tf.keras.layers.MaxPool2D(pool_size=2, strides=2))

model.add(tf.keras.layers.Conv2D(filters=128, kernel_size=3, padding="same", activation="relu"))
model.add(tf.keras.layers.Conv2D(filters=128, kernel_size=3, activation="relu"))
model.add(tf.keras.layers.MaxPool2D(pool_size=2, strides=2))

model.add(tf.keras.layers.Conv2D(filters=256, kernel_size=3, padding="same", activation="relu"))
model.add(tf.keras.layers.Conv2D(filters=256, kernel_size=3, padding="same", activation="relu"))
model.add(tf.keras.layers.MaxPool2D(pool_size=2, strides=2))

model.add(tf.keras.layers.Conv2D(filters=512, kernel_size=3, padding="same", activation="relu"))
model.add(tf.keras.layers.Conv2D(filters=512, kernel_size=3, activation="relu"))
model.add(tf.keras.layers.MaxPool2D(pool_size=2, strides=2))




C:\Users\WILSONA\anaconda3\envs\monai\lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [10]:
model.add(tf.keras.layers.Dropout(0.25)) #dropping 25% of the layers of neurons for the input layer to avoid overfittng

In [11]:
model.add(tf.keras.layers.Flatten())

In [12]:
model.add(tf.keras.layers.Dense(units=1500,activation="relu"))

In [13]:
model.add(tf.keras.layers.Dropout(0.4)) #dropping 40% of the nueron on the output layer

In [14]:
#output layer
model.add(tf.keras.layers.Dense(units=38,activation="softmax"))

# compiling our model

In [15]:
model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.0001),
              loss="categorical_crossentropy",
              metrics=["accuracy"])


In [16]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                 │ (None, 128, 128, 32)   │           896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_1 (Conv2D)               │ (None, 126, 126, 32)   │         9,248 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d (MaxPooling2D)    │ (None, 63, 63, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_2 (Conv2D)               │ (None, 63, 63, 64)     │        18,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_3 (Conv2D)               │ (None, 61, 61, 64)     │        36,928 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_1 (MaxPooling2D)  │ (None, 30, 30, 64)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_4 (Conv2D)               │ (None, 30, 30, 128)    │        73,856 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_5 (Conv2D)               │ (None, 28, 28, 128)    │       147,584 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_2 (MaxPooling2D)  │ (None, 14, 14, 128)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_6 (Conv2D)               │ (None, 14, 14, 256)    │       295,168 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_7 (Conv2D)               │ (None, 14, 14, 256)    │       590,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_3 (MaxPooling2D)  │ (None, 7, 7, 256)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_8 (Conv2D)               │ (None, 7, 7, 512)      │     1,180,160 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_9 (Conv2D)               │ (None, 5, 5, 512)      │     2,359,808 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_4 (MaxPooling2D)  │ (None, 2, 2, 512)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 2, 2, 512)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 2048)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 1500)           │     3,073,500 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 1500)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 38)             │        57,038 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 7,842,762 (29.92 MB)

 Trainable params: 7,842,762 (29.92 MB)

 Non-trainable params: 0 (0.00 B)

In [50]:
training_history = model.fit(x=training_set,validation_data=validation_set,epochs=10)

Epoch 1/10
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 18990s 9s/step - accuracy: 0.2695 - loss: 2.6475 - val_accuracy: 0.7933 - val_loss: 0.6700
Epoch 2/10
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 18227s 8s/step - accuracy: 0.7865 - loss: 0.6999 - val_accuracy: 0.8740 - val_loss: 0.3944
Epoch 3/10
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 18852s 9s/step - accuracy: 0.8848 - loss: 0.3704 - val_accuracy: 0.9346 - val_loss: 0.2125
Epoch 4/10
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 18753s 9s/step - accuracy: 0.9246 - loss: 0.2404 - val_accuracy: 0.9496 - val_loss: 0.1563
Epoch 5/10
  34/2197 ━━━━━━━━━━━━━━━━━━━━ 4:30:19 7s/step - accuracy: 0.9514 - loss: 0.1631

KeyboardInterrupt: 

In [7]:
from tensorflow.keras.models import load_model
model = load_model("plant_model.h5")


In [9]:
from tensorflow.keras.models import load_model

# Load the model
model = load_model("plant_model.h5")

# Compile the model again with desired metrics
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Now the model's metrics are set, and you can use it for evaluation or further training


In [17]:
train_loss, train_acc =model.evaluate(training_set)
print('Training accuracy:', train_acc)

2197/2197 ━━━━━━━━━━━━━━━━━━━━ 4321s 2s/step - accuracy: 0.9650 - loss: 0.1051
Training accuracy: 0.9658581614494324


In [18]:
val_loss, val_acc = model.evaluate(validation_set)
print('Validation accuracy:', val_acc)

550/550 ━━━━━━━━━━━━━━━━━━━━ 1090s 2s/step - accuracy: 0.9499 - loss: 0.1544
Validation accuracy: 0.9461643695831299


In [19]:
model.save('trained_plant_disease_model.keras')

In [ ]:
training_history.history 


In [ ]:
import json
with open('training_hist.json','w') as f:
  json.dump(training_history.history,f)

In [ ]:
print(training_history.history.keys())

In [ ]:
epochs = [i for i in range(1,11)]
plt.plot(epochs,training_history.history['accuracy'],color='red',label='Training Accuracy')
plt.plot(epochs,training_history.history['val_accuracy'],color='blue',label='Validation Accuracy')
plt.xlabel('No. of Epochs')
plt.title('Visualization of Accuracy Result')
plt.legend()
plt.show()

In [28]:
class_name = validation_set.class_names
class_name

['Apple___Apple_scab',
 'Apple___Black_rot',
 'Apple___Cedar_apple_rust',
 'Apple___healthy',
 'Blueberry___healthy',
 'Cherry_(including_sour)___Powdery_mildew',
 'Cherry_(including_sour)___healthy',
 'Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot',
 'Corn_(maize)___Common_rust_',
 'Corn_(maize)___Northern_Leaf_Blight',
 'Corn_(maize)___healthy',
 'Grape___Black_rot',
 'Grape___Esca_(Black_Measles)',
 'Grape___Leaf_blight_(Isariopsis_Leaf_Spot)',
 'Grape___healthy',
 'Orange___Haunglongbing_(Citrus_greening)',
 'Peach___Bacterial_spot',
 'Peach___healthy',
 'Pepper,_bell___Bacterial_spot',
 'Pepper,_bell___healthy',
 'Potato___Early_blight',
 'Potato___Late_blight',
 'Potato___healthy',
 'Raspberry___healthy',
 'Soybean___healthy',
 'Squash___Powdery_mildew',
 'Strawberry___Leaf_scorch',
 'Strawberry___healthy',
 'Tomato___Bacterial_spot',
 'Tomato___Early_blight',
 'Tomato___Late_blight',
 'Tomato___Leaf_Mold',
 'Tomato___Septoria_leaf_spot',
 'Tomato___Spider_mites Two-spotted_